export const SELECT_KEY_INDEX = 'SELECT_KEY_INDEX';
export const SELECT_CAPO = 'SELECT_CAPO';
export const OPEN_CHORDS_MODAL_ACTION = 'OPEN_CHORDS_MODAL_ACTION';
export const CLOSE_CHORDS_MODAL_ACTION = 'CLOSE_CHORDS_MODAL_ACTION';